### ISSUE TITLE
Switch sides on overview image?

### ISSUE THREAD

**Issue by nicjar** [NBISweden/Knox-ePouta#3]
Not to be a pain in the *ss, but I think it confuses people that you've located Finland to the west of Sweden

https://github.com/NBISweden/Knox-ePouta/blob/master/reports/img/overview.png

**Comment by silverdaz** [comment]
Jag har fått kommentar från Jonas och Antti. Fixed in the paper, but I had forgotten the docs.md link. Fixed now.
